### ISSUE TITLE
Php 7.x compatibility

### ISSUE THREAD

**Issue by albertovincenzi** [robertogallea/laravel-greenpass#3]
Are you sure that php8.0 is the minimum requirement?
If the package is compatible with laravel >= 6.0, I think would be better to make it compatible with php 7.x

**Comment by robertogallea** [comment]
Hi Alberto, 
I remember it was due to a dependence. I will into it. Thank you. However, saying it is compatible with L6 does not imply that it must be compatible with php 7.x. Am I wrong?

**Comment by albertovincenzi** [comment]
You are absolutely right: php 8 support starts from L6.
I also checked the dependencies and its due to the package you wrapped which I also checked and asked about php8 as minimum requirement. Currently just few projects which are in production adopt php8 so I think is just common sense to make php7 compatible IF POSSIBLE.

**Comment by albertovincenzi** [comment]
One more hint: I checked the wrapped library and I must say is not that good: it decodes the green pass and thats all.
I saw this: https://github.com/herald-si/verificac19-sdk-php

I would say is great compared to the other one and checks also if the green pass is valid (signature) or not.

**Comment by robertogallea** [comment]
I would have liked to write my own decoder but I did not have time to do it. The library you mention did not exist yet (at least I think) when I wrote this package. However, you're right, it seems much better. Would you mind rewrap it and make a PR? I don't know when I will be able to do it.

**Comment by robertogallea** [comment]
I know only a few projects actually support php8 but it should be a request for the wrapped package (unless the other package is wrapped instead). Again, please submit a PR, or you have to wait until I can do some rewriting. However, thank you for the useful feedback!

**Comment by albertovincenzi** [comment]
Thanks for your feedback. I already started working on a wrapper package. Once it will be tested and ready for production, I will release it

**Comment by robertogallea** [comment]
Hi, I managed to wrap the alternative lib. If you want to, please take a look and give your considerations. Thanks!
